# Generated by Django 4.0.2 on 2022-03-27 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('icon', models.ImageField(default='images/light.svg', upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='proceduretype',
            name='icon',
            field=models.ImageField(default='images/doctor.svg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('date_time', models.DateTimeField()),
                ('comment', models.TextField(null=True)),
                ('severity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.severity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
