# Generated by Django 4.0.2 on 2022-03-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_appointment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduretype',
            name='icon',
            field=models.ImageField(default='images/doctor.svg', upload_to=''),
        ),
    ]
