# Generated by Django 4.0.2 on 2022-03-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_pic_alter_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(default='images/jessica.svg', upload_to=''),
        ),
    ]
